"""Tags for the seed entries whose source line carried no category prefix.

Data, not logic -- edit freely. Keyed by title, because the same title recurs
("Time" sits on 7, 12, 24, 60 and 365) and always means the same thing.
Anything missing here simply arrives untagged and gets tagged in the wiki.
"""
SEED_TAGS = {
    "Trinity: The Father, The Son (Jesus Christ), and The Holy Spirit": ["RELIGION"],
    "Four Horsemen of the Apocalypse": ["RELIGION", "MYTH"],
    "Maroon 5": ["MUSIC"],
    "5 Seconds of Summer": ["MUSIC"],
    "Chanel N°5": ["BRAND"],
    "Six Degrees of Separation": ["RULE"],
    "Time": ["UNIT"],
    "9 Muses": ["MYTH"],
    "Cloud 9": ["SLANG"],
    "A Cat has 9 Lives": ["MYTH"],
    "12 Steps": ["RULE"],
    "PG-13": ["MOVIE"],
    "NC-17": ["MOVIE"],
    "애창곡": ["MUSIC", "SLANG"],
    "18-Hole Golf Course": ["SPORTS"],
    "Blackjack": ["GAME"],
    "Birthday Paradox": ["MATH"],
    "Michael Jordon": ["PERSON", "SPORTS"],
    "24K": ["UNIT"],
    "25 to Life": ["SLANG"],
    "Forever 27 Club": ["MUSIC", "MEME"],
    "Feb 29th.": ["UNIT"],
    "Rule 34": ["MEME", "RULE"],
    "36계 줄행랑": ["SLANG", "HISTORY"],
    "37% Rule": ["MATH", "RULE"],
    "Sum41": ["MUSIC"],
    "C41": ["TECH"],
    "Jackie Robinson": ["PERSON", "SPORTS"],
    "AK47": ["TECH", "HISTORY"],
    "49재": ["RELIGION"],
    "50 Cent": ["MUSIC", "PERSON"],
    "Area 51": ["PLACE"],
    "1 Year = 52 Weeks": ["UNIT"],
    "59FIFTY": ["BRAND"],
    "60갑자": ["HISTORY", "UNIT"],
    "64괘": ["RELIGION", "MYTH"],
    "Route 66": ["PLACE"],
    "Meme": ["MEME"],
    "Rule of 72": ["MATH", "RULE"],
    "이세돌 vs 알파고 4국 78수": ["HISTORY", "TECH"],
    "대한민국 국가 번호": ["TECH", "PLACE"],
    "X86": ["TECH"],
    "Piano": ["MUSIC"],
    "Angle": ["MATH"],
    "Basic Introduction; Class 101": ["SLANG"],
    "108번뇌": ["RELIGION"],
    "135 Film": ["TECH", "UNIT"],
    "Blink-182": ["MUSIC"],
    "SHA-256": ["TECH"],
    "Portra 400": ["BRAND", "TECH"],
    "Not Found": ["TECH", "MEME"],
    "Marijuana": ["SLANG", "MEME"],
    "Magazine FourFourTwo": ["SPORTS", "BRAND"],
    "SS501": ["MUSIC"],
    "Number of the Beast": ["RELIGION"],
    "720P": ["TECH", "UNIT"],
    "731부대": ["HISTORY"],
    "Jackpot": ["SLANG"],
    "808 Drum Machine": ["MUSIC", "TECH"],
    "1080P": ["TECH", "UNIT"],
    "Leet": ["MEME", "SLANG"],
    "Taxicab number": ["MATH"],
    "2160p": ["TECH", "UNIT"],
    "Cicada 3301": ["MEME", "TECH"],
    "Golden Ratio": ["MATH"],
    "e": ["MATH"],
    "π": ["MATH"],
    "τ": ["MATH"],
    "Gravitational Force": ["SCIENCE", "UNIT"],
    "Axial Tilt": ["SCIENCE"],
    "Marathon": ["SPORTS", "UNIT"],
    "0도": ["SCIENCE", "UNIT"],
    "Wi-Fi": ["TECH"],
    "1기압": ["SCIENCE", "UNIT"],
    "Speed of Light": ["SCIENCE", "UNIT"],
    "Heinrich's law": ["RULE"],
    "Vision": ["SCIENCE", "SLANG"],
    "Deuce": ["SPORTS"],
    "Pareto Principle": ["RULE", "MATH"],
    "Apple iPhone": ["BRAND", "TECH"],
    "Apple AppleWatch": ["BRAND", "TECH"],
}
